faucetからのTPC取得＆送金方法ガイド作成
chaintope/tapyrus-pages pull request #11
Opened 2022-06-29 01:52 UTC by oshikawatkm

#4 faucetからのTPC取得＆送金方法ガイドを作成しました。

2022-06-30 05:35 UTC, azuchi reviewed
このガイドですが、現在トップページにリンクされている↓

https://site.tapyrus.chaintope.com/network/

のページにTapyrusのTestnetのパラメーターの説明と一緒に記載する形にできますか？

2022-07-06 05:16 UTC, azuchi requested changes

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +Chaintopeが運営するテスト用のネットワークは以下のようなパラメータを持ちます。
```suggestion
Chaintopeが運営するテスト用のネットワークは以下のパラメータを使用しています。
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +Chaintopeが運営するテスト用のネットワークは`1939510133`をネットワークIDとして持ちます。
```suggestion
Chaintopeが運営するテスト用のネットワークは`1939510133`をネットワークIDとして使用しています。
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +#### Tapyrusモード
```suggestion
#### Tapyrusの動作モード
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +したがって、Chaintopeが運営するテスト用のネットワークは`prod`モードです。
```
Tapyrusでは、プロダクション環境用の`prod`と開発環境用`dev`の2種類の動作モードが用意されており、Chaintopeが運用するテスト用のネットワークは`prod`モードで動作しています。
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +実験用に1つのTapyrusノードを起動する場合は`dev`モードを指定します。
```suggestion
開発やテストでローカルで単一のTapyrusノードを実行する場合は`dev`モードの使用を推奨します。  
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +ここからはChaintopeが提供するTapyrusのテストネット(ID: 1939510133)上でTapyrusの通貨であるTPCを送受金する方法について解説します。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +本記事ではTapyrusノードの環境構築方法については解説しません。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +[Tapyrus-seeder](https://github.com/chaintope/tapyrus-seeder){:target="_blank"}は、Tapyrusネットワーク用のクローラーで、内蔵のDNSサーバーを介して信頼できるノードのリストを公開します。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +Tapyrusでは複数のプロダクションネットワークを構築することができます。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +ネットワークIDは、それぞれのTapyrusネットワーク識別子です。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +各Tapyrusネットワークは一意のジェネシスブロックを持ちます。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +tapyrus-cli以下のような構成で入力を行います。
```suggestion
tapyrus-cliでは、以下のような構成でコマンドを実行します。
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +tapyrus-cliコマンドの詳細は`tapyrus-cli -h`で確認できます。
```suggestion
tapyrus-cliの各コマンドの詳細は`tapyrus-cli -h`で確認できます。
```

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +##### tapyrus-cliコマンド実行時のパスについて {#notes-tapyrus-cli-path}
基本的に、tapyrus-cli、tapyrusdにはパスが通ってる前提でいいと思うので、ここは不要です。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +## Wallet, Addressの作成 {#create-wallet-address}
コマンド以外の説明時は、Wallet→ウォレット、Address→アドレスの表記に統一しましょうか。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +`0.00000000`と表示され、TPCを所有していないことが分かります。
上記、改行はなくていいです。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +Faucetに表示された`Current Balance`が0の時、TPCを取得することができません。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +`getbalance`コマンドを用いて、再度所有するTPCの量を確認します。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +同様に`listunspent`コマンドを用いて、UTXOを確認します。
改行不要

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +トランザクションの詳細情報確認には`gettransaction`コマンドを実行します。
gettransaction使うのって何故でしたっけ？getrawtransactionだけでもいいような。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +実行時、`-rpcwallet`オプションで使用するWalletを指定します。
`loadwallet`コマンドでウォレットをロードしていれば、`rpcwallet`不要だったりしませんか？

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +このアドレスはfaucetからのコイン受取時に使用するため控えておいてください。
それぞれ改行不要です。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +
ここでP2PKHアドレスが生成されることに触れておいてください。

2022-07-06 05:16 UTC, azuchi commented on _pages/network.md
> +
通過の単位がBTC, satoshiの関係がそのままTPC、tapyrusという単位になっていることに触れておいてください。

2022-07-06 05:20 UTC, azuchi commented on _pages/network.md
> +```
```suggestion
```javascript
```
CLIでも戻り値がJSONの場合は、javascript指定するとハイライト効いて良いかと思います。

2022-07-06 07:57 UTC, oshikawatkm commented on _pages/network.md
> +トランザクションの詳細情報確認には`gettransaction`コマンドを実行します。
一通りよく使うコマンドの紹介のつもりで追加しましたが、不要であれば削除します。

2022-07-06 08:42 UTC, oshikawatkm commented on _pages/network.md
> +実行時、`-rpcwallet`オプションで使用するWalletを指定します。
手順通り`createwallet`を実行した流れで、`rpcwallet`なしで`getbalance`実行すると以下のエラーが表示されます。
```
$ tapyrus-cli getbalance
error code: -19
error message:
Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).
Try adding "-rpcwallet=<filename>" option to tapyrus-cli command line.
```
そのため、`loadwallet`を実行すると以下のエラーが表示されます。
```
$ tapyrus-cli loadwallet wallet1
error code: -4
error message:
Wallet file verification failed: Error loading wallet wallet1. Duplicate -wallet filename specified.
```
となります。
自分の認識では`rpcwallet`は使用するwalletの指定のために必要だったと思います。

2022-07-06 08:50 UTC, azuchi commented on _pages/network.md
> +実行時、`-rpcwallet`オプションで使用するWalletを指定します。
了解です。このまま進めましょう。

2022-07-06 08:56 UTC, azuchi commented on _pages/network.md
> +トランザクションの詳細情報確認には`gettransaction`コマンドを実行します。
`getrawtransaction`使うのであれば、そっちだけで良いかと思います。`getrawntransaction <txid> true or 1`で、同様にJSON形式のデータが確認可能です。

2022-07-07 05:45 UTC, azuchi commented on _pages/network.md
> +Chaintopeが運営するテスト用のネットワークでは`0x74839A75`をマジックバイトとして使用します。
マジックバイトはネットワークIDから導出される点を追記してください。

https://github.com/chaintope/tapyrus-core/blob/f38edadce63aac1bfa964c279baf7a6f5f0e9d1f/doc/tapyrus/network_id_and_magic_bytes.md#calculation-of-the-magic-bytes

2022-07-08 05:23 UTC, azuchi approved these changes

2022-07-08 05:23 UTC, merged